config/routes.rb
Rails.application.routes.draw do

  resources :navigations
  namespace :dashboard do
    get '/', to: 'dashboard#index'
    resources :promos
    resources :vehicles
    resources :car_dealerships
  end

  namespace :brand do
    get '/:id', to: 'brands#show', as: 'profile'
  end

  namespace :member do
    get '/:id', to: 'members#show', as: 'member'
  end

  devise_for :users, controllers: {sessions: 'sessions' }
  devise_for :brand_users, controllers: { sessions: 'sessions', registrations: 'users/registrations' }, skip: [:sessions]
  root to: 'home#index'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand_user.rb
class BrandUser < User
  #has_many :vehicles
end

app/models/car_dealership.rb
class CarDealership < ApplicationRecord
end

app/models/navigation.rb
class Navigation < ApplicationRecord
end

app/models/promo.rb
class Promo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  #belongs_to :brand_user
  mount_uploader :cover, CoverUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :permitted_parameters, if: :devise_controller?

  protected

  def permitted_parameters

    registration_params = [
        :username,
        :firstname,
        :lastname,
        :doc_type,
        :doc_number,
        :phone_number,
        :gender,
        :date_of_birth,
        :fullname,
        :company,
        :website,
        :logo,
        :cover
    ]
    login_params = [:login, :username]

    if params[:action] == 'update'
      devise_parameter_sanitizer.permit(:account_update, keys: registration_params)
    elsif params[:action] == 'new'
      devise_parameter_sanitizer.permit(:sign_in, keys: login_params)
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.permit(:sign_up, keys: registration_params)
    end

  end
end

app/controllers/brand/brands_controller.rb
class Brand::BrandsController < ApplicationController

  def show
    @user = BrandUser.find(params[:id])
  end

end

app/controllers/dashboard/promos_controller.rb
class Dashboard::PromosController < ApplicationController
  layout 'dashboard'

  def index
    @promos = Promo.all
  end

  def create
    @promo = Promo.new(promos_params)
    if @promo.save
      render json: @promo
    else
      render json: @promo.errors, status: :unprocessable_entity
    end
  end

  private
  def promos_params
    params.require(:promo).permit(:name, :firstDate, :dueDate, :vehicle_id, :user_id, :description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Vehicle.all
  end
end

app/controllers/member/members_controller.rb
class Member::MembersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    rtn = super
    sign_in(resource.type.underscore, resource.type.constantize.send(:find, resource.id)) unless resource.type.nil?
    rtn
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end
end

app/helpers/car_dealerships_helper.rb
module CarDealershipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigations_helper.rb
module NavigationsHelper
  def navigation
    @navigation = Navigation.all
  end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autonexo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/home_header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="dashboard-main-content">
    <%= react_component 'DashboardMenu', data: navigation, request: request.path %>
    <div class="wrap-content">
      <div class="wrap-inner">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/partials/_banner_items.html.erb
<% products.each do |p| %>
<div class="item">
  <img src="https://s3.amazonaws.com/autonexo/static/banner.jpg" alt="<%= p.vehicle %>"/>
  <div class="main-info">
    <div class="container">
      <h2><%= p.vehicle %></h2>
      <span class="text-white"><%= number_to_currency(p.price,  unit: '$ ') %></span>
    </div>
  </div>

</div>
<% end %>

app/views/partials/_home_header.html.erb
<% if current_brand_user %>
  <%= react_component 'HomeHeader', current_user: current_brand_user %>
<% elsif current_user %>
    <%= react_component 'HomeHeader', current_user: current_user %>
<% else %>
    <%= react_component 'HomeHeader', current_user: '' %>
<% end %>